AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  EnvName:
    Type: String
  HostingBucketName:
    Type: String
Resources:
  S3:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.ap-northeast-1.amazonaws.com/mybucketwebcloud/4cf2098e15bcfbbb7edad9ed98c5237b.template
      Parameters:
        BucketName:
          Fn::Join:
          - '-'
          - - Ref: EnvName
            - Ref: HostingBucketName
  CloudFront:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.ap-northeast-1.amazonaws.com/mybucketwebcloud/bf2398b43e783d27dd3c61943d4f3b37.template
      Parameters:
        BucketName:
          Fn::Join:
          - '-'
          - - Ref: EnvName
            - Ref: HostingBucketName
