AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  EnvName:
    Type: String
  HostingBucketName:
    Type: String

Resources:
  S3:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: resources/s3.yml
      Parameters:
        BucketName: !Join ["-", [!Ref EnvName, !Ref HostingBucketName]]
  CloudFront:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: resources/cloudfront.yml
      Parameters:
        BucketName: !Join ["-", [!Ref EnvName, !Ref HostingBucketName]]
