AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  BucketName:
    Type: String
Resources:
  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Origins:
          - Id: CustomOrigin
            DomainName: !Sub '${BucketName}.s3-website-ap-northeast-1.amazonaws.com'
            CustomOriginConfig:
              HTTPPort: 80
              OriginProtocolPolicy: http-only
        Enabled: true
        DefaultRootObject: index.html
        Logging:
          Bucket: 'accesslogs-dev-hosting-web.s3.amazonaws.com'
          IncludeCookies: 'false'
          Prefix: !Sub 'myprefix/'
        CustomErrorResponses:
          - ErrorCachingMinTTL: 300
            ErrorCode: 404
            ResponseCode: 200
            ResponsePagePath: /404.html
          - ErrorCachingMinTTL: 300
            ErrorCode: 500
            ResponseCode: 200
            ResponsePagePath: /500.html
        Comment: !Sub '${AWS::StackName}-distribution'
        DefaultCacheBehavior:
          TargetOriginId: CustomOrigin
          ForwardedValues:
            QueryString: false
          DefaultTTL: 300
          MaxTTL: 300
          MinTTL: 300
          ViewerProtocolPolicy: redirect-to-https
      Tags:
        - Key: CloudFormationArn
          Value: !Sub '${AWS::StackName}'